
# docker-compose up -d  //.docker-compose
services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    environment:
      - ENV=development
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app
  tensorboard:
    image: tensorflow/tensorflow
    volumes:
      - ./model/logs:/logs  
    command: tensorboard --logdir=/logs --bind_all
    ports:
      - "6006:6006"




